### ISSUE TITLE
No credits/social/online segment on mobile

### ISSUE THREAD

**Issue by nabijaczleweli** [Galactim/Sudoku#7]
Consider:
![desktop SS](https://user-images.githubusercontent.com/6709544/48923238-2a3a0b00-eead-11e8-8c50-3c2ee0476969.png)

Whereas:
![mobile SS](https://user-images.githubusercontent.com/6709544/48923239-31611900-eead-11e8-892e-117c80997ce5.png)

**Comment by who-is-apo** [comment]
Fixed.

**Comment by nabijaczleweli** [comment]
Is it?
![SS](https://user-images.githubusercontent.com/6709544/48962832-5ffef280-ef86-11e8-92d3-fb13bd93a5ef.png)
